version: '3.4'

services:

  cointracker.db.mongo:
    image: mongo
    container_name: Cointracker.Db.Mongo
    ports:
      - 27017:27017
    volumes:
      - "mongodb:/data/db"
   
  cointracker.bus.rabbitmq:
    image: rabbitmq:management
    container_name: Cointracker.Bus.RabbitMQ
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq


  cointracker.api.coinlist:
    image: ${DOCKER_REGISTRY-}cointrackerapicoinlistcontrollers
    ports:
      - 50001:80
    build:
      context: .
      dockerfile: src/CoinTracker.API.CoinList/CoinTracker.API.CoinList.Controllers/Dockerfile

  cointracker.api.wallets:
    image: ${DOCKER_REGISTRY-}cointrackerapiwalletscontrollers
    ports:
      - 50002:80
    build:
      context: .
      dockerfile: src/CoinTracker.API.Wallets/CoinTracker.API.Wallets.Controllers/Dockerfile

volumes:
  mongodb:
  rabbitmqdata: