version: '3.4'

services:

  cointracker.bus.rabbitmq:
    image: rabbitmq:management
    container_name: Cointracker.BUS.RabbitMQ
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

  cointracker.db.mongo:
    image: mongo
    container_name: Cointracker.DB.Mongo
    ports:
      - 27017:27017
    volumes:
      - "mongodb:/data/db"

  cointracker.api.coinlist:
    image: ${DOCKER_REGISTRY-}cointrackerapicoinlistcontrollers
    ports:
      - 50001:80
    build:
      context: .
      dockerfile: src/CoinTracker.API.CoinList/CoinTracker.API.CoinList.Controllers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__host=cointracker.db.mongo
      - RabbitMqSettings__host=cointracker.bus.rabbitmq

  cointracker.api.wallets:
    image: ${DOCKER_REGISTRY-}cointrackerapiwalletscontrollers
    ports:
      - 50002:80
    build:
      context: .
      dockerfile: src/CoinTracker.API.Wallets/CoinTracker.API.Wallets.Controllers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__host=cointracker.db.mongo

volumes:
  mongodb:
  rabbitmqdata: