version: '3.4'

services:
  cointracker.api.coinlist:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__host=cointracker.db.mongo
      - RabbitMqSettings__host=cointracker.bus.rabbitmq
    ports:
      - "80"

