version: '3.4'

services:

  cointracker.db.mongo:
    image: mongo
    container_name: Cointracker.Db.Mongo
    ports:
      - 27017:27017
    volumes:
      - "mongodb:/data/db"

  cointracker.api.coinlist:
    image: ${DOCKER_REGISTRY-}cointrackerapicoinlistcontrollers
    ports:
      - 50001:80
    build:
      context: .
      dockerfile: src/CoinTracker.API.CoinList/CoinTracker.API.CoinList.Controllers/Dockerfile

volumes:
  mongodb:
