apiVersion: apps/v1
kind: Deployment
metadata:
  name: cointracker-api-coinlist-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cointracker-api-coinlist
  template:
    metadata:
      labels:
        app: cointracker-api-coinlist
    spec:
      containers:
        - name: cointracker-coinlist-db-mongo
          image: mongo
          volumeMounts:
          - mountPath: /data/db
            name: mongodb-coin
