apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-coin-volumeclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-wallet-volumeclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi