name: "Create cluster using KinD"
on: [push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install kubectl
      uses: steebchen/kubectl@v2.0.0
    - name: Set up Minikube
      uses: kube-actions/setup-kind@v1.2.0
      with:
        kind-version: "v0.11.1"
    - name: Start Minikube
      run: |
        minikube start
    - name: Stop Minikube
      run: |
        minikube stop
