name: "Create cluster using KinD"
on: [push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
   
    - name: Install kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
    - name: Create Kubernetes cluster
      run: |
        kind create cluster --name test-cluster --config kind-config.yaml
    - name: Configure kubectl
      run: |
        kubectl cluster-info --context kind-test-cluster
    - name: Deploy app to Kubernetes
      run: |
        cd k8s
        kubectl apply -f local-pvc.yaml
        kubectl apply -f cointrackercoin-depL.yaml
    - name: Wait service up
      run: | 
        kubectl cluster-info dump
        until kubectl rollout status deployment/cointracker-api-coinlist-depl --timeout=30s; do
          echo 'Waiting for example-deployment to be ready...'
          kubectl get deploy
          sleep 1
        done
        kubectl get services
        kubectl get nodes -o=jsonpath='{.items[0].status.addresses[0].address}'
        kubectl get services cointracker-api-coinlist -o=jsonpath='{.spec.ports[0].targetPort}'
    - name: Test Api
      run: |
        NODE_PORT=$(kubectl get services cointracker-api-coinlist -o=jsonpath='{.spec.ports[0].targetPort}')
        NODE_IP=$(kubectl get nodes -o=jsonpath='{.items[0].status.addresses[0].address}')
        echo "http://$NODE_IP:$NODE_PORT/api/coin"
        curl -I http://$NODE_IP:$NODE_PORT/api/coin
        
    - name: Delete Kunbernetes cluster
      run: |
        kind delete cluster
