name: "Create cluster using KinD"
on: [push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Install kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
    - name: Create Kubernetes cluster
      run: |
        kind create cluster --name test-cluster --config kind-config.yaml
    - name: Configure kubectl
      run: |
        kubectl cluster-info --context test-cluster
    - name: Delete Kunbernetes cluster
      run: |
        kind delete cluster
