name: "Create cluster using KinD"
on: [push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Install kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
    - name: Create Kubernetes cluster
      run: |
        kind create cluster --name test-cluster --config kind-config.yaml
    - name: Configure kubectl
      run: |
        kubectl cluster-info --context kind-test-cluster
    - name: Deploy app to Kubernetes
      run: |
        cd k8s
        kubectl apply -f rabbitmq-depl.yaml
        kubectl apply -f cointrackercoin-depL.yaml
    - name: Wait service up
      run: | 
        kubectl get deploy
        kubectl logs pod/cointracker-api-coinlist-depl-7486747b84-9trd4 -c cointracker-coinlist-db-mongo
        until kubectl rollout status deployment/cointracker-api-coinlist-depl --timeout=30s; do
          echo 'Waiting for example-deployment to be ready...'
          kubectl get deploy
          kubectl logs pod/cointracker-api-coinlist-depl-7486747b84-9trd4 -c cointracker-coinlist-db-mongo
          sleep 1
        done
    - name: Test Api
      run: |
        curl http://localhost/api/coin/
    - name: Delete Kunbernetes cluster
      run: |
        kind delete cluster
