name: "Create cluster using KinD"
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up KIND
      uses: docker/setup-kind@v1
      with:
        config: |
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            image: kindest/node:v1.22.2
            extraPortMappings:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP

    - name: Install Helm
      uses: azure/setup-helm@v1.0.3

    - name: Deploy Coin Tracker API
      run: |
        kubectl create deployment cointrackerapi --image=sas1989/cointrackerapicoinlist:latest
        kubectl expose deployment cointrackerapi --type=LoadBalancer --port=80

    - name: Test Coin Tracker API
      uses: crazy-max/curl@v1
      with:
        args: -sSL http://localhost:8080/api/coin
