name: "Create cluster using KinD"
on: [push]

env:
  IMAGE_NAME: sas1989/cointrackerapicoinlist:latest

jobs:
  test_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v1
        with:
          version: '1.22.3'
          download: true

      - name: Retrieve Docker image
        run: |
          kubectl create deployment cointracker --image=$IMAGE_NAME
          kubectl rollout status deployment/cointracker

      - name: Make request to Docker image
        run: |
          POD_NAME=$(kubectl get pods --selector=app=cointracker --output=jsonpath={.items..metadata.name})
          kubectl port-forward $POD_NAME 8080:80 &
          sleep 5
          curl http://localhost:8080/health
